FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

# Устанавливаем зависимости
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt \
    && pip install --no-cache-dir -e /app

COPY ./src /app/src

EXPOSE 5000

CMD ["python", "src/app.py"]