services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_TOKEN=""
    user: "${USER_ID}:${GROUP_ID}"
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow-server